overleaf/real-time

app/coffee/ConnectedUsersManager.coffee
test/unit/coffee/ConnectedUsersManagerTests.coffee

ioredis returns a blank object, {}, if there is no key with hgetall.
Previously, node-redis returned nil. So we need to check for a blank
object as well as a nil object.

Don't return a user if there is no entry

---

Jenkinsfile

Quick PR to run acceptance tests for real-time on new builds server. This was inadvertently omitted when I first brought across the config.

Jg realtime acceptance tests

---

test/acceptance/coffee/JoinDocTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

Fixes the `joinDoc` tests for the new function signature and add tests for encoding options

Fix joinDoc tests & add encoding tests

---

test/acceptance/coffee/helpers/MockDocUpdaterServer.coffee
test/acceptance/coffee/helpers/MockWebServer.coffee

avoid confusion if existing process is already listening on the port

exit if mock servers fail to start

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/Router.coffee
app/coffee/WebsocketController.coffee

errors from docupdater or client can be downgraded to warnings.

convert errors to warnings

---

config/settings.defaults.coffee

Switches dev environment to use web_v2 container instead of web_sl container now that the SL container is not needed in most dev workflows.
Connects to sharelatex/sharelatex-dev-environment#121

Switch dev env to use v2 port instead of SL

---

app/coffee/WebsocketController.coffee
test/unit/coffee/WebsocketControllerTests.coffee

If a user joins in the middle of a user's session and they have neither first name nor last name set, they were labelled as Anonymous instead of by their email address as they should be.
Sends an empty string for the user's name instead of "Anonymous". Users who are truly anonymous are dealt with in web (See related PR).
Fixes https://github.com/sharelatex/web-sharelatex-internal/issues/910
Relates to https://github.com/sharelatex/web-sharelatex-internal/pull/1501
Deploy the web one first https://github.com/sharelatex/web-sharelatex-internal/pull/1501
@jdleesmiller was pairing with me on it at one point so he will probably be interested in what happened with it in the end

Nameless logged in user labelled as anonymous

---

test/acceptance/coffee/ClientTrackingTests.coffee

Fix this failing acceptance test
```
1 failing
1) clientTracking
when an anonymous client updates its cursor location
should tell other clients about the update:
AssertionError: expected [ Array(1) ] to deeply equal [ Array(1) ]
+ expected - actual
{
"column": 36
"doc_id": "463debbfb87ce56cf0cecb39"
"id": "gLgdkM0T7x-yJRu6p1F-"
-    "name": ""
+    "name": "Anonymous"
"row": 42
"user_id": "anonymous-user"
}
]
at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:393:19)
at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
at Context.<anonymous> (test/acceptance/js/ClientTrackingTests.js:202:41)
```
Which happened as a result of the changes done to change how anonymous users are handled in `WebSocketController` in …

Fix test to accommodate changes to anonymous users

---

app.coffee
app/coffee/DocumentUpdaterController.coffee
app/coffee/WebsocketLoadBalancer.coffee
config/settings.defaults.coffee

this keeps the pub sub channel ticking along happily. Likely only an issue in staging but it means there is always traffic happening. I think the root cause is ghostunnel but this solves the issue to an adequate degree. 
https://github.com/sharelatex/overleaf-google-ops/issues/176
Increases the amount of traffic through redis, but even with 30 instances it is only an extra 0.5ms which is nothing for redis.
updates on https://staging-google.sharelatex.com should keep working and not timeout

setup continualPubsubTraffic to keep pub sub happy

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/EventLogger.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/EventLoggerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Check message ids on pubsub message events to detect duplicate and out-of-order events.  
NA
Connects to https://github.com/overleaf/sharelatex/issues/1627 and https://github.com/sharelatex/web-sharelatex-internal/pull/1639
Adds a `EventLogger` module with a `checkEventOrder` method, keeps track of counters for each host key.  Clears out stale host keys every 100000 events, deleting any which have not received updates in the past hour.
Low (as long as it doesn't crash) - doesn't modify messages.
NA
No special issues, will work whether message id is present or not.
Errors will be logged in sentry
@henryoswald

add check for duplicate events

---

app.coffee
app/coffee/DocumentUpdaterController.coffee
app/coffee/EventLogger.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/EventLoggerTests.coffee

This will log and skip duplicate events, as well as the client list, hopefully giving us more of a handle of why we are sending them to the client.
Also adds a `/debug/events?count=N` endpoint to allow logging of next  `N` events on pubsub channels.
NA
https://github.com/overleaf/sharelatex/issues/1700
Minimal changes
Low
NA
NA
NA
New log entries for duplicate events

handle duplicate events

---

app.coffee
app/coffee/DocumentUpdaterController.coffee
app/coffee/HealthCheckManager.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/DocumentUpdaterControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

This adds a health check to the realtime `applied-ops` and `editor-events` pubsub channels, piggybacking on the existing `continualPubSubTraffic` code.  
The health check adds a unique id to each continual traffic message and checks that it is received once (only) within a timeout of 3 seconds.    If we begin to see duplicate messages (as in overleaf/sharelatex#1700) or no messages then we should restart real-time. 
It also monitors the latency of the pubsub channel as we do not currently track this.  
I have increased the frequency of the continual pubsub traffic to one message every 20 seconds, to match the default health check frequency. 
NA
overleaf/sharelatex#1700
Self-contained change mainly in `HealthCheckManager`.
Low
NA
NA
Grafana metrics for …

add health check to pubsub channels

---

app.coffee
npm-shrinkwrap.json
package.json

This PR adds support for node version 7 and above.
`process.EventEmitter` has been deprecated in node6 and was removed in node7. It is still available via the events lib. The `socket.io` release `0.9.18` includes an incomplete patch for this deprecation [1], `0.9.19` fixes the patch.
`socket.io` can support flash clients. These may request a policy file, which is provided by a package that has a similar usage of the `EventEmitter`.
I could not find any flash in the web-app, removing the transport seems to be straight forward then. 
---
[1] See the upstream PR https://github.com/socketio/socket.io/pull/2790

[misc] add support for node 7+

---

app/coffee/DrainManager.coffee
app/coffee/HttpApiController.coffee

Allow a slower drain by increasing the polling interval from 1 second to 1/rate seconds when the rate is less than 1 per second.
NA
NA
Small change
Only affects drain
NA
NA
NA
NA
@henryoswald

allow fractional drain rate

---

app/coffee/DocumentUpdaterManager.coffee
test/unit/coffee/DocumentUpdaterManagerTests.coffee

Document updater 404s are not indicative of a problem, but just of the client
trying to connect to a deleted document, which is easy to trigger. We
log a warning instead.
I also changed the assertions for errors because comparing errors is a tricky business. In our case, tests would pass even if the error messages were not those expected.
This solves overleaf/issues#1788
One way I found to reproduce the problem:

Do not log error on doc updater 404

---

app/coffee/WebsocketController.coffee
test/unit/coffee/WebsocketControllerTests.coffee

Unauthorised access now logs a warning instead of an error.
Fixes https://github.com/overleaf/issues/issues/1791
None

Downgraded unathorised log to warning

---

app.coffee

we can't send double health check events to same redis, it causes
health check duplicate errors. Commit just sends health check data to
pub sub pair and then sends non health check traffic to cluster to keep
the connection open

Ho pubsub healthcheck

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/RedisClientManager.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/DocumentUpdaterControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Allow multiple redis configurations for pubsub by replacing the single `rclient`s used for pubsub by a list `rclientList`. 
The `applied-ops` and `editor-events` channels on both redis configurations are subscribed to, the services creating events on those (docupdater and web) can be switched over gracefully.
NA
https://github.com/overleaf/google-ops/issues/333
Health checks not extended yet TBD
Needs testing locally
NA
Deploy this in advance and move everyone over to this version - then other services can be switched when needed. 
Docupdater update rate
@henryoswald @mans0954 @jdleesmiller

support multple redis instances for pubsub

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/WebsocketLoadBalancer.coffee

Remove the additional `unused` redis client for cluster, so that only the primary `pubsub` redis sentinel client is used.
Add a check to skip the per-client metrics when there is only one client.
Retaining the infrastructure to support multiple clients in case we need to do any further migrations. 
NA
https://github.com/overleaf/google-ops/issues/333
Small change.
Low
NA
NA
NA

remove redis cluster from realtime

---

app/coffee/EventLogger.coffee

Now that the volume of out-of-order events is lower we can log them for debugging.
Small change
Low
NA
NA
NA
Log for any of these entries in the logs after 24 hours.

log out of order events now that the rate is lower

---

app.coffee
socket.io.patch.js

Workaround for a bug in socket.io v0.9.16 until we can upgrade to socket.io v2.  The bug causes the websocket connection to crash whenever the framesize is exactly 65536, and the editor cannot recover from this. As soon as you come back into the project you usually get the same error.
https://github.com/overleaf/issues/issues/2017
Small change
Low, there is a version check and the code is copied from the original file in socket.io with one change to the condition `>65536` and a console.log.
NA
NA
NA

monkeypatch socket.io to fix frame handler in v0.9.16

---

app/coffee/RoomManager.coffee
test/acceptance/coffee/LeaveDocTests.coffee

This is a fix for the error seen in overleaf/issues#2112.  The `join` to the socket.io room was not executed until after the redis `subscribe` had completed, so that it was possible for a client to leave the room before actually joining it.  
The correct ordering is to join and leave the room synchronously on each request, so that we can use the number of clients in the room as a reference count for whether we need to be subscribed or not.  When a client joins a room we do want wait for the redis subscribe to complete before returning the response to the client.
NA
overleaf/issues#2112 and overleaf/real-time#65
This is just moving the `join` for the socket.io room up front. I've added an acceptance test that the error is no longer triggered when a `leave` request immediately follows a …

fix async behaviour of join/leave

---

app/coffee/RoomManager.coffee
test/acceptance/coffee/LeaveDocTests.coffee
test/unit/coffee/RoomManagerTests.coffee

Fix to ignore spurious leaveDoc requests (where a client sends a delayed leaveDoc request after a reconnection).
NA
https://github.com/overleaf/issues/issues/2112
Small change, ignore requests to leave a room if the client is not actually present in it.
Low
NA
NA
NA
The "not subscribed - shouldn't happen" error in sentry should be resolved by this.
@henryoswald

ignore spurious requests to leave other docs

---

socket.io.patch.js

As part of Server Pro revival we need to be able to run all the services under the same node version. This is the only service that fails to bootstrap, and this patch fixes it. I haven't tested the behaviour yet, only the bootstrap.
Contributes to https://github.com/overleaf/issues/issues/2043

Patched EventEmitter for socket.io compatibility with Node >= 7

---

app/coffee/ConnectedUsersManager.coffee
app/coffee/WebsocketController.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/ConnectedUsersManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

Refresh the client list on demand to reduce the number of stale clients appearing.  We allow one second for the other real-time processes to update the client list following a `clientTracking.refresh` message in the project `editor-events` toom.  We exclude any connectedUser that hasn't been updated in the last 10 seconds from the list of connected users.
NA
Low, affects connected user display only.
NA
NA
NA
NA

refresh client list

---

app/coffee/Router.coffee

Record the number of connected clients for each real-time process
NA
Copied from DrainManager to get the number of connected clients
Low, metric only
NA
NA
NA
`socket-io.clients`

add connected client count metric

---

app.coffee
app/coffee/DocumentUpdaterManager.coffee
app/coffee/Router.coffee

Reject new connections when shutdown is in progress.  Sends a 'retry' message back to the client for a quick reconnect.  This is handled by https://github.com/overleaf/web-internal/pull/2077
NA
https://github.com/overleaf/google-ops/issues/438
Small change.
Client connections will be rejected, they need to be able to connect elsewhere.  
NA
Needs web change to go out first
NA
NA

status on shutdown

---

app.coffee

Clean up stray unused variable, `forceDrainMsDelay`, convert the setting to a number and use that for `shutdownDrainTimeWindow`.

clean up unused variable, convert setting to number

---

app/coffee/ConnectedUsersManager.coffee
test/unit/coffee/ConnectedUsersManagerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Minimal fix for https://github.com/overleaf/issues/issues/2179,  only return users with a user_id.
NA
https://github.com/overleaf/issues/issues/2179
Longer cleanup PR at https://github.com/overleaf/real-time/pull/76, I won't deploy that today.
Smallest change to fix this.
Low
NA
NA
NA
NA

only show connected users with a user_id

---

app/coffee/Errors.coffee
app/coffee/Router.coffee
app/coffee/WebApiManager.coffee
test/acceptance/coffee/JoinProjectTests.coffee
test/acceptance/coffee/helpers/MockWebServer.coffee
test/unit/coffee/WebApiManagerTests.coffee

As part of the testing for overleaf/issues#2176, we discovered that it's easy to hit the project-join rate limit when reconnecting lots of times. When that happens, the connection fails pretty hard and you see a big scary warning.
This patch flags 429 as a retryable error, so that we can add logic to the client to handle this more gracefully.
overleaf/issues#2176
Added an `Errors` mechanism so that we can (in the future) generate multiple types of retryable error.
cc @timothee-alby, @henryoswald

Generate retryable error when hitting rate limits in web

---

app/coffee/WebApiManager.coffee
app/coffee/WebsocketController.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/WebApiManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Track the `isRestrictedUser` flag on clients  then, don't send new chat messages and new comments to those restricted clients.
We do this because we don't want to leak private information (email addresses
and names) to "restricted" users, those who have read-only access via a
shared token.
- Part of https://github.com/overleaf/issues/issues/2319
- Sibling of https://github.com/overleaf/web-internal/pull/2206
It's real-time, so pretty high. We're now using Async in the broadcast-to-clients loop, which could have a performance impact.
- Depends on https://github.com/overleaf/web-internal/pull/2206 to have any effect.
- Keep an eye on cpu and memory in real-time

Track the `isRestrictedUser` flag on clients

---

app/coffee/WebApiManager.coffee
app/coffee/WebsocketController.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/WebApiManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Reverts overleaf/real-time#81
After deploying, I noticed that this behaviour doesn't seem quite right. I think this PR for real-time is still correct, but there are problems with the web UI.
Specifically, if the restricted user comes along to a project that already has comments, they see the comments as part of the UI. They can then reply to them and will see a spinner, whilst the comments are sent to the other users in the project.
Really, we need to add a PR to web to not show comments when the project is loaded, in order for this to be tied up properly. Otherwise, things just look a bit broken.
Example, from a read-write user:
From a read-only user:

Revert "Track the `isRestrictedUser` flag on clients"

---

app/coffee/WebApiManager.coffee
app/coffee/WebsocketController.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/WebApiManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Resurrection of https://github.com/overleaf/real-time/pull/81, and following on from its reversion in https://github.com/overleaf/real-time/pull/85.
Track the `isRestrictedUser` flag on clients  then, don't send new chat messages and new comments to those restricted clients.
We do this because we don't want to leak private information (email addresses
and names) to "restricted" users, those who have read-only access via a
shared token.
- Hide review comments from restricted users when they join a document
- Part of https://github.com/overleaf/issues/issues/2319
- Sibling of https://github.com/overleaf/web-internal/pull/2306 (current)
- Sibling of https://github.com/overleaf/web-internal/pull/2206 (old)
It's real-time, so pretty high. We're now using Async in the broadcast-to-clients loop, …

Filter "comments" if restricted user.

---

app.coffee

Log the shutdown messages as warnings and pass the signal to the signal handler correctly.

improve shutdown logging

---

app.coffee

`EPIPE` when writing to the client sholdn't be considered a fatal error - it's just us trying to talk to a dead client.
Patch to log a warning instead of shut down, when this occurs.
See overleaf/issues#1833

Don't shut down on uncaught EPIPE

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/DrainManager.coffee
app/coffee/Router.coffee
app/coffee/WebsocketLoadBalancer.coffee

Emitting messages to clients probably shouldn't crash the server. This patch adds a try/catch around attempts to communicate with the client (via `client.emit`) so that this (hopefully) doesn't happen.
See overleaf/issues#1833

Add try/catch around all client emissions

---

app/coffee/WebsocketLoadBalancer.coffee

the emit is happening asynchronously after the client list is computed,
so clients may have disconnected in the intervening time.

avoid emitting when client not connected

---

app.coffee

We've seen `ECONNRESET` coming up the same way as `EPIPE` which should also not be fatal.
One thing to consider: If the clients don't get cleaned up at this point we might see some heavy leakage. Added a metric to track this.
See overleaf/issues#1833

Handle ECONNRESET in the same way as EPIPE

---

app/coffee/RoomManager.coffee

https://github.com/overleaf/real-time/pull/67 moved the client join out of the branch for empty rooms. Unfortunately the join in the branch for already present clients was not removed.
With socket.io v2 this seems to contribute to an unstable acceptance test that challenges a race condition of the join/leave logic.
https://github.com/overleaf/real-time/blob/2060a2fdc5c6badfa92a717a6ff35dfe91ad9f20/test/acceptance/coffee/LeaveDocTests.coffee#L63-L65
https://github.com/overleaf/real-time/pull/67
@briangough

[RoomManager] drop duplicate joining of entities

---

test/acceptance/coffee/helpers/RealTimeClient.coffee

The acceptance test helper methods are callback based and also return Promises. Future mocha versions do not like this. This PR proposes to drop the implicitly returned Promise.
Affects tests only

[misc] test/acceptance: RealTimeClient: drop implicit Promise return

---

test/acceptance/coffee/SessionTests.coffee

The SessionTests depend on a connected client that might then get disconnected in case the session is missing (which is not the case). The test setup should wait for the client to connect.

[misc] test/acceptance: SessionTests: wait for the client to connect

---

test/acceptance/coffee/LeaveProjectTests.coffee

socket.io v2 clients do not have an `.id` field after disconnection.
This PR caches the value in a variable.
Affects tests only

[misc] test/acceptance: LeaveProjectTests: work around destructed client

---

test/acceptance/coffee/ApplyUpdateTests.coffee
test/acceptance/coffee/ReceiveUpdateTests.coffee

Some of the redis settings are misaligned in the tests. This is not that much of an issue as we run just one redis instance for the acceptance tests.

[misc] test/acceptance: use the correct redis instances

---

test/acceptance/coffee/LeaveDocTests.coffee

The socket.io client.join/client.leave logic would:
- in v2: emit the join/leave event first, before updating the internal client state.
- in v0: update the internal state, then fire the event
Upon a leave request the RoomManager would check the internal state of the client for an existing membership in a given room. In case of no membership, the request would perform no operation.
This does not play nice with the test that joins and leaves at almost the same time.
In v0 the race condition is unlikely to appear:
| time | join              | leave            |
| ---- | ----------------- | ---------------- |
| 0    | req start         |                  |
| 1    | update membership | req start        |
| 2    | fire join         | check membership |
| 3    |                   | fire leave …

[LeaveDocTests] fix a test that is not stable with socket.io v2

---

test/acceptance/coffee/ReceiveUpdateTests.coffee

This PR extends the `ReceiveUpdateTests` in adding a 2nd project and a 3rd user that joins this 2nd project but not the first one.
The intend is to check for cross project leaks from the message fan-out.
Sending messages and errors from doc-updater is tested -- the errors are paired with a disconnect.

[misc] test/acceptance: ReceiveUpdateTests: add 2nd project/3rd client

---

test/acceptance/coffee/DrainManagerTests.coffee

This PR adds tests for logic of the DrainManager.
There are other clients connected but there is no api endpoint to disconnect them at this time.
I do have patches available that implement this and will schedule them after this PR.
We can then lower the timeout in line 52 as the drain will schedule the reconnect for the two clients immediately -- currently the clients from other tests are asked to reconnect too, and there is a 1s delay in between the drain runs.

[misc] test/acceptance: add tests for the draining of connections

---

test/acceptance/coffee/ApplyUpdateTests.coffee
test/acceptance/coffee/ClientTrackingTests.coffee
test/acceptance/coffee/DrainManagerTests.coffee
test/acceptance/coffee/JoinDocTests.coffee
test/acceptance/coffee/JoinProjectTests.coffee
test/acceptance/coffee/LeaveDocTests.coffee
test/acceptance/coffee/LeaveProjectTests.coffee
test/acceptance/coffee/ReceiveUpdateTests.coffee
test/acceptance/coffee/SessionTests.coffee
test/acceptance/coffee/helpers/SocketIoUtils.coffee

This is in preparation for the socket.io upgrade with breaking changes in the client API.
I am proposing to abstract some of the client access into helper functions. Upon upgrading the version, only the helper function will need changes and the rest of the tests remain unchanged, easing code review.

[misc] test/acceptance: use helpers for unified socket.io client access

---

test/acceptance/coffee/helpers/RealtimeServer.coffee

The acceptance tests are very verbose, even tho `LOG_LEVEL` is set to `ERROR` in the docker-compose files. This is due to a hard coded override to `LOG_LEVEL=INFO` in a (broken [1]) acceptance tests helper.
This PR proposes to remove the hard coded value and let's the developer set the level depending on their needs via the docker-compose files.
---
[1] we do not export the express app in `app.coffee`, hence all the logic in there is void.

[misc] test/acceptance: silence the logger

---

app/coffee/HttpController.coffee
test/acceptance/coffee/HttpControllerTests.coffee

This is in preparation for the socket.io upgrade.
`client.rooms` includes the socket id/client id in socket.io v2. The added tests lock in the existing behavior of not including the id.
Non-existing clients yielded an empty client view previously [1]. I changed the behavior to return a status code of 404 instead.
Low, the client view route is used in acceptance tests and might be used for debugging
---
[1] `io.sockets.socket()` creates a new Socket instance in case it can not find an existing for the provided id. This Socket instance is likely never freed, creating a memory leak when debugging in production. https://github.com/socketio/socket.io/blob/41b9a7e45d62ead3b4b36dc38cc8c03882ecc577/lib/namespace.js#L202-L208

[HttpController] return 404 in case of a missing client

---

app/coffee/HttpApiController.coffee
app/coffee/Router.coffee
test/acceptance/coffee/DrainManagerTests.coffee
test/acceptance/coffee/helpers/RealTimeClient.coffee

This is the suggested followup PR for https://github.com/overleaf/real-time/pull/108
It implements the http api routes for disconnecting a single client, paired with acceptance tests helper to disconnect all clients.
This functionality is then used to cleanup previous clients before starting to drain/reconnect clients.
The DrainManager can reconnect the clients of the DrainManagerTests immediately and does not have to cycle through all the other clients before them.
We can drop the added timeout spec for the individual DrainManagerTest cases now.
https://github.com/overleaf/real-time/pull/108
Low, added functionality and changes tests

[perf] test/acceptance: DrainManagerTests: cleanup previous clients

---

app/coffee/WebsocketLoadBalancer.coffee

Followup from https://github.com/overleaf/real-time/pull/113#discussion_r384380729
This PR removes the overhead from using `async.eachLimit` when a simple synchronous loop works too.
_Previously there were async operations happening inside the loop, which required the use of `async.eachLimit` to limit the number of concurrent actions._
https://github.com/overleaf/real-time/pull/113

[perf] WebsocketLoadBalancer: move back to a sync loop for msg fan out

---

test/acceptance/coffee/ReceiveUpdateTests.coffee

This should be the last PR before the socket.io upgrade.
It merely extends the test coverage for changed logic in the socket.io upgrade.

[misc] test/acceptance: ReceiveUpdateTests: test remotely sent update

---

app.coffee
config/settings.defaults.coffee

As per the title. Proxys in front of `real-time` may poll the health status and push traffic to the pod until it shows a failing state. Reconnect requests should not go to the same pod. We have to wait for the proxy to observe that a given pod is going down soon, before we can start with draining.
Default is do not delay the draining. Adjust via the environment variable `STATUS_CHECK_INTERVAL`.
https://github.com/overleaf/dev-environment/pull/324
Low
- see https://github.com/overleaf/dev-environment/pull/324

[misc] let proxys observe an upcoming shutdown before starting to drain

---

app/coffee/DocumentUpdaterManager.coffee
app/coffee/SafeJsonParse.coffee
app/coffee/WebsocketController.coffee
config/settings.defaults.coffee
test/acceptance/coffee/ApplyUpdateTests.coffee
test/unit/coffee/DocumentUpdaterManagerTests.coffee
test/unit/coffee/SafeJsonParseTest.coffee
test/unit/coffee/WebsocketControllerTests.coffee

We should limit inbound socket.io traffic.
Large updates get pushed to redis, pulled by doc-updater and discarded then.
The frontend will not receive a confirmation for the update and will push the
update again and again, until it gets disconnected by real-time when the
rejection from doc-updater comes in as an 'otUpdateError'.
Related and also included in this PR:
We can push an update to doc-updater that is larger than a single doc is
allowed to be (2mb). The confirmation from doc-updater would get rejected
however, the frontend will never see the confirmation and send the update
again and again.
The limit is set to two doc-sizes (delete and insert new full doc) plus the
maximum size of ranges: 2*2mb + 3mb.
In theory we should add JSON encoding overhead to the limit.
But I could not …

[misc] limit update size

---

app.coffee
app/coffee/ChannelManager.coffee
package-lock.json
package.json
test/unit/coffee/ChannelManagerTests.coffee

Sibling of https://github.com/overleaf/document-updater/pull/130
https://github.com/overleaf/document-updater/pull/130
This PR includes a bump of the metrics module version to 2.6, which adds `Metrics.summary`.
Low
- added unit test
`redis.publish.applied-ops`
`redis.publish.editor-events`
`redis.publish.cluster-continual-traffic`

[misc] track redis pub/sub payload sizes on publish

---

app/coffee/DocumentUpdaterManager.coffee
test/unit/coffee/DocumentUpdaterManagerTests.coffee

Add queue throughput metric for pendingUpdates (added to queue)
NA
https://github.com/overleaf/issues/issues/2882
and
https://github.com/overleaf/document-updater/pull/127
Adds metric only
Low.  Realtime so any exception would be very bad.
NA
Combine this with any other pending realtime deploys, to reduce the number of times we shift users onto a new realtime process.
NA
Add redis.pendingUpdates `push` metric to redis dashboard.
NA

add metric for pendingUpdates queue

---

app/coffee/Router.coffee
app/coffee/WebsocketController.coffee

For https://digital-science.slack.com/archives/G6Q45PYQL/p1587468755015700
There seem to be events coming in after the socket entered the 'disconnecting' state (before 'disconnect'). It should be OK to leave the `ol_context` on the client and let v8 clean it up as it destructs the client.
Low, race condition see slack.

[Router] gracefully set and do not reset the ol_context

---

app/coffee/DocumentUpdaterController.coffee
app/coffee/WebsocketLoadBalancer.coffee

This reverts commit 8026003f8e9dab506d1a8a3e6e5f41188555a6bb
See this discussion:
https://github.com/overleaf/real-time/pull/117/files/818a3e509e5906a0d75b994b820cdef06fce68e2..be289b66821f1228a9bcdd6a29837c7cd8e62d64#r387073018
We assumed that `process.nextTick` would not allow for clients to 'disappear'/disconnect in between calling`io.clients(ROOM)`  and us processing the result synchronously.
https://digital-science.slack.com/archives/G6Q45PYQL/p1587634527021500 proved different.
https://github.com/overleaf/real-time/pull/117
Low, added safe guard

[misc] bring back the safe guards when processing the .clients() result

---

.editorconfig
app/coffee/DocumentUpdaterController.coffee
app/coffee/RoomManager.coffee
app/coffee/WebsocketController.coffee
app/coffee/WebsocketLoadBalancer.coffee
test/unit/coffee/DocumentUpdaterControllerTests.coffee
test/unit/coffee/RoomManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee
test/unit/coffee/WebsocketLoadBalancerTests.coffee

Implement https://digital-science.slack.com/archives/G6256GXGS/p1587995985009900?thread_ts=1587995558.008500&cid=G6256GXGS
Getting a client list and processing the contents of it is now safe -- the clients in the list are all connected and there are no other clients that may joined/left the room as we process the list.
This fixes the race condition in socket.io-adapter of calculating the room list and returning the list via `process.nextTick`.
https://github.com/socketio/socket.io-adapter/blob/ae23c7ef4cd1b1793121b5af0376686a2ba2deea/index.js#L210
Given that we check the connected state of all clients in the new helper `RoomManager.getClientsInRoomSync` it is safe to revert #127 .
#127 
The unit tests are probably useless when upgrading socket.io, but I added them anyways.
High. …

[misc] hack around process next tick

---

.editorconfig
app/coffee/RoomManager.coffee

Followup for #128 
`client.rooms` is not safe to use.
<details>
the implementation in socket.io is prone to race conditions:
The adapter will get updated immediately from joining, but the client
local state (.rooms) is updated via process.nextTick.
Given that NodeJS can process multiple network events in the same event
loop cycle, we can join a project and disconnect in the same cycle.
We will not pick up the room (we just joined) for leaving.
</details>
#128 
Low.

[misc] get the list of rooms a client is in in a synchronous fashion

---

.editorconfig
app/coffee/ChannelManager.coffee
package-lock.json
package.json
test/unit/coffee/AuthorizationManagerTests.coffee
test/unit/coffee/ChannelManagerTests.coffee
test/unit/coffee/WebApiManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

For https://github.com/overleaf/issues/issues/3002
Upon detecting a redis pub/sub subscribe failure we should discard the 'subscribed' state for the entity and let the next request start from scratch.
Currently based onto #129 
https://github.com/overleaf/issues/issues/3002
`sinon` < 2 does not support promises. So I went the long way of upgrading it for proper stub support https://github.com/overleaf/real-time/commit/3c92b937f9430175d7c51660e03c507635448e88. This required some fixes to the way we check error messages -- in fact sinon did not check the error message and lots of tests failed after the upgrade https://github.com/overleaf/real-time/commit/d9570fee70701a5f431c39fdbec5f8bc5a7843fe.
I could not get the unhandled promise rejection warning in the unit tests to disappear, even tho …

[misc] clear on subscribe failure

---

app.coffee

https://digital-science.slack.com/archives/G6256GXGS/p1588666706113600
> The heartbeat timeout for socket.io changed from v0 (60s) to v2 (5s). Given that the browser is not putting the tab into full sleep, but just makes it slow, we could just bump that timeout back up.
>
> v0: https://github.com/socketio/socket.io/blob/41b9a7e45d62ead3b4b36dc38cc8c03882ecc577/lib/manager.js#L78
> v2: https://github.com/socketio/engine.io/blob/dcdbccb3dd8a7b7db057d23925356034fcd35d48/lib/server.js#L26 
> In case the connection is bad the user will eventually get an out-out-sync error (with 100 ops in between their update and others, that's really slow then) or it will just work fine.
v0 handshake:
https://github.com/socketio/socket.io/blob/41b9a7e45d62ead3b4b36dc38cc8c03882ecc577/lib/manager.js#L808
``` …
```

[misc] restore the default pingTimeout of 60s from socket.io v0

---

app/coffee/WebsocketController.coffee
test/unit/coffee/WebsocketControllerTests.coffee

We are seeing random spikes in the metrics from clients connecting, but never actually authenticating/joining. Upon disconnect we are calling leaveProject to cleanup, which may not be actually needed, when the client did not call joinProject yet.
I attached a `joinedProject` attribute to the client when the web api call succeeded. Only there after we are actually populating client params and joining rooms.
Putting the `joinedProject` flag into the regular client params would require indent changes to get the value back in an async way.
Alternative approach: We could move `metrics.inc "editor.leave-project"` into `Utils.getClientAttributes` and use a regular param then.
High, missing cleanup could lead to memory leaks.
- added unit test

[WebsocketController] skip leaveProject when joinProject didn't complete

---

app/coffee/ChannelManager.coffee
test/acceptance/coffee/LeaveProjectTests.coffee
test/acceptance/coffee/PubSubRace.coffee
test/unit/coffee/ChannelManagerTests.coffee

Backport of the simplified strict-sequence from #133
Please see the discussion over there for more details.
Chained onto #136 for promise support with stubs.
#133
High, every `joinProject` and `joinDoc` triggers a subscribe redis request -- previously only the first collaborator on the same pod triggered the subscribe, following users joining the same project/doc on a given pod used the existing subscription.
- added new acceptance tests with a race of joinDoc vs leaveDoc requests
- extended existing acceptance tests to check redis subscribes
- added unit tests
Watch redis dashboard and upstream redis dashboard for CPU usage.

[misc] backport strict sequence of redis (un)subscribe

---

.editorconfig
app/coffee/ChannelManager.coffee
app/coffee/WebsocketController.coffee
test/acceptance/coffee/PubSubRace.coffee
test/unit/coffee/ChannelManagerTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

master and v2 diverged quite a bit, so I had to revert a few changes and restore most of them after the merge.
- revert and restore the leaveProject bailout for clients that did not join previously, this change has a conflict with the client context gathering #135 
- drop sinon upgrade to v2 from v0 branch, the package lock changes conflict with v2 #136 
- revert whitespace changes from #137
- drop cleanup of subscribe failure https://github.com/overleaf/real-time/pull/130 in favor of #137 
The PubSubRace test suite is not stable with v2 and a followup PR will fix that.
broken PubSubRace build https://console.cloud.google.com/cloud-build/builds/604379c6-d5d0-4f49-b3b1-ed0f97989b72?project=overleaf-ops
rebuild passes: https://console.cloud.google.com/cloud-build/builds/24ed3e55-a8c4-43de-8f …

[misc] merge master into v2

---

app/coffee/RoomManager.coffee
app/coffee/WebsocketController.coffee
test/acceptance/coffee/EarlyDisconnect.coffee
test/acceptance/coffee/LeaveDocTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

Chained onto https://github.com/overleaf/real-time/pull/139 which merges v0 (including a pub/sub race test suite)
This PR fixes racing join requests and disconnect events. The processing of disconnect events skips a `process.nextTick` call (2 vs 3 calls) and hence we will process disconnect before a join request (or other rpc call).
- joinProject
-  bails out at start, after web api call
- previous impact: could leave dangling pub/sub subscribes
- joinDoc
- bails out at start, after redis pub/sub join (1), after doc-updater call
- previous impact: could leave dangling pub/sub subscribes, e.g. see [this failed build](https://console.cloud.google.com/cloud-build/builds/604379c6-d5d0-4f49-b3b1-ed0f97989b72;step=2?project=overleaf-ops)
- updateClientPosition
- bails out at start
- previous …

[misc] stop processing requests as we detect a client disconnect

---

test/acceptance/coffee/helpers/RealtimeServer.coffee
test/unit/coffee/ChannelManagerTests.coffee

The ChannelManagerTests are very verbose due to a missing logger stub -- lost in https://github.com/overleaf/real-time/pull/137
Acceptance tests: backport https://github.com/overleaf/real-time/pull/110
https://github.com/overleaf/real-time/pull/110

[misc] downgrade logging when running tests

---

app/coffee/RoomManager.coffee
app/coffee/WebsocketController.coffee
test/acceptance/coffee/EarlyDisconnect.coffee
test/acceptance/coffee/LeaveDocTests.coffee
test/unit/coffee/WebsocketControllerTests.coffee

Backport https://github.com/overleaf/real-time/pull/140
https://github.com/overleaf/real-time/pull/140
The interfaces for v0 and v2 differ, in the the connected state is stored on the lower level in v0 `client.socket.connected`.
But v0 also expose the state inverted on top-level via `client.disconnected`.
https://github.com/socketio/socket.io/blob/41b9a7e45d62ead3b4b36dc38cc8c03882ecc577/lib/socket.js#L151-L156
Some indents are off, but decaff/prettier will take care of that eventually.

[backport] 140: stop processing requests as we detect a client disconnect

---

app/coffee/Router.coffee
test/acceptance/coffee/RouterTests.coffee

Add acceptance tests for #141 (v2) and #147 (backport).
#141 and #147 (backport)
https://github.com/overleaf/issues/issues/3067
_Also add a note on the low log level of the `attrs` for `'unexpected arguments'`._
Low, adds tests.

[misc] add test cases for the validation of the callback argument

---

app/coffee/HttpController.coffee
test/acceptance/coffee/HttpControllerTests.coffee

Backport #111 which adds acceptance tests for the HttpController (and changes the behavior for missing clients to not create a new client, but return a 404)
#111

[backport] 111 HttpController: 404 for missing clients and add tests

---

app/coffee/RoomManager.coffee
test/unit/coffee/RoomManagerTests.coffee

I stumbled across this unhandled rejection during a rework of the RoomManager
in my fork. I am really unsure how we missed it previously.
```
result = Promise.all([<Promise that rejects eventually>]) # rejection 1
result.then () -> RoomEvents.emit(eventName)              # rejection 2
result.catch (err) -> RoomEvents.emit(eventName, err)     # handle r1
```
As shown above, the second rejection remains unhandled. The fix is to
chain the `.catch()` onto the `.then()` Promise.
Low.
- added unit test

[misc] RoomManager: emitOnCompletion: properly handle Promise rejections

---

app/js/Router.js
config/settings.defaults.js

For https://github.com/overleaf/issues/issues/3263
https://github.com/overleaf/issues/issues/3263
Low. Only adds new rpc endpoint.
- checkout `jpa-expose-hostname` in the dev-env
- open the editor
- `_ide.socket.emit('debug.getHostname', console.log)`

[misc] optionally expose the hostname in the 'debug.getHostname' rpc

---

app.js
app/js/HttpApiController.js

For https://github.com/overleaf/issues/issues/2965
https://github.com/overleaf/issues/issues/2965
High, but `app/js/HttpApiController.js` is covered by acceptance tests.
Running the acceptance tests locally showed the deprecation warning -- in CI they are not logged for some reason :shrug: .
<details>
<pre>
real-time$ make test_acceptance
...
DrainManagerTests
✓ should have disconnected all previous clients
with two clients in the project
starting to drain
express deprecated res.send(status): Use res.sendStatus(status) instead app/js/HttpApiController.js:35:9
</pre>
</details>
- start dev-env
- edit project

[misc] fix express deprecations

---

package-lock.json
package.json

For https://github.com/overleaf/issues/issues/3371
Pull in https://github.com/overleaf/socket.io/pull/4 and https://github.com/overleaf/socket.io-client/pull/2
> Gracefully access transport methods, when the transport/WebSocket may not exist yet/anymore.
https://github.com/overleaf/issues/issues/3371
https://github.com/overleaf/socket.io/pull/4
https://github.com/overleaf/socket.io-client/pull/2
The socket.io packages are not tagged yet, I am using branches for testing in real-time first.
Before merging I will remove the `jpa-test-release-` prefix.
The integrity hash downgrades are expected, see https://github.com/overleaf/issues/issues/3252#issuecomment-665096798
High, this is changing the connect code path -- I verified that the editor load, aka has a working connection.
See …

[misc] bump socket.io and socket.io-client: harden cleanup

---

.gitignore
.npmrc
buildscript.txt

For https://github.com/overleaf/dev-environment/pull/380
Blocking local npm-install broke the Server CE/Pro build.
The npmrc will now live in a git-ignored file, generated by the Makefile of the dev-env.
https://github.com/overleaf/dev-environment/pull/380
Closes https://github.com/overleaf/overleaf/issues/764
None for production.

[misc] bump the dev-env to 3.3.1

---

app.js

For https://github.com/overleaf/issues/issues/3419
We were seeing invalid socket access on potentially gone client socket. This lead to a shutdown of all real-time nodes.
As an intermediate fix we are going to swallow the seen error codes, that are specifically tied to invalid socket access.
The continuous pub-sub traffic/health-check ensures that we notice errors from out-going redis traffic that ends up with the same error code.
https://github.com/overleaf/issues/issues/3419
Technically `EHOSTUNREACH` and `ETIMEDOUT` should go into a
'disconnected_read' metric. But this would require changes to
dashboards and a larger diff.
High. Breaking the signal listener could crash real-time too frequently. I am adding entries into the check list only.
We do not have a reproducer yet.
The codes …

[app] ignore errors from accessing disconnected client sockets

---

package-lock.json
package.json

Followup for #173 
For https://github.com/overleaf/issues/issues/3371
Pull in https://github.com/overleaf/socket.io/pull/5 and https://github.com/overleaf/socket.io-client/pull/3
> - harden the cleanup of sockets/transports
>    Delayed inflight of packages may trigger a heartbeat after closing the transport.
#173 
https://github.com/overleaf/issues/issues/3371
https://github.com/overleaf/socket.io/pull/5
https://github.com/overleaf/socket.io-client/pull/3
The socket.io packages are not tagged yet, I am using branches for testing in real-time first.
Before merging I will remove the `jpa-test-release-` prefix.
High, this is changing the health-check code path. It is non trivial to get into the in https://github.com/overleaf/socket.io-client/pull/3 described race condition tho.
See …

[misc] bump socket.io and socket.io-client

---

app.js
app/js/DrainManager.js
config/settings.defaults.js

For https://github.com/overleaf/issues/issues/3419
The shutdown process asks clients to reconnect, but some clients may be broken/ignore the message.
This leaves the real-time processes in an unhealthy state indefinitely.
This PR waits for all clients to get asked for a reconnect and after a configurable delay `GRACEFUL_RECONNECT_TIMEOUT_MS` it disconnects them forcefully.
The default delay is 45s + 30s. The 45s are [coming from the frontend](https://github.com/overleaf/web/blob/eb84e0d4eb2ea83e9f31753b10297e71ae3d02c2/frontend/js/ide/connection/ConnectionManager.js#L32) -- it permits users to keep editing. I added 30s to allow users with a bad internet connectivity to receive the graceful reconnect message and flush their send queue.
https://github.com/overleaf/issues/issues/3419
Low. …

[misc] forcefully disconnect from shutdown process

---

package.json

As per the title. All my cloud builds for the reworked logging were failing due to timeouts. The tests are completing just fine locally.
https://digital-science.slack.com/archives/C20TZCMMF/p1598009512014800
None for production.

[misc] increase the timeout for unit tests -- CI boxes are too slow

---

app/js/AuthorizationManager.js
app/js/DocumentUpdaterManager.js
app/js/Errors.js
app/js/Router.js
app/js/SafeJsonParse.js
app/js/SessionSockets.js
app/js/WebApiManager.js
app/js/WebsocketController.js
package.json
test/unit/js/DocumentUpdaterManagerTests.js
test/unit/js/SafeJsonParseTest.js
test/unit/js/WebApiManagerTests.js
test/unit/js/WebsocketControllerTests.js

Part of https://github.com/overleaf/issues/issues/3265
Instead of stuffing context on the error object this PR is leveraging OError info context. A few custom errors do not have context yet, but we may add some soon -- e.g. which action triggered a `NotAuthorizedError`.
A follow-up PR could refactor the `error.message` comparisons into error-instance checks.
Chained onto #183 to make the unit tests pass in CI -- they pass locally without #183 .
https://github.com/overleaf/issues/issues/3265
I tried to keep the log messages identical, but for some errors this was not possible -- e.g. those which stuff context into the message like the response status.
Medium. All error code paths.
- run unit/acceptance tests
- editor works
- join not existing doc/project via the browser console -- e.g. …

[misc] migrate to custom OErrors

---

app/js/Router.js

Part of https://github.com/overleaf/issues/issues/3265
The `doc_id` is not part of the `ol_context` (and was not part of the socket.io context before that). It may come from the caller context instead. Additionally add the `doc_id` from the `leaveDoc` rpc.
Chained onto #183 to make the unit tests pass in CI -- they pass locally without #183 .
https://github.com/overleaf/issues/issues/3265
Low. May help in debugging failing joinDoc/leaveDoc rpcs.
- run unit/acceptance tests
- editor works
- join not existing doc via the browser console -- e.g. `_ide.socket.emit('joinDoc, '5f0a31aa0e69950001550000', console.log)` and see `doc_id` in the logs.

[misc] add/bring back doc_id in error context

---

app/js/Router.js

Part of https://github.com/overleaf/issues/issues/3265
The ol_context patch changed the priority of client context and rpc
context.
This lead to the (possibly missing) project_id of the client context
overwriting the project_id of the rpc context.
REF: f1d55c0a5437a518e9f4617473caed9ba928e648
Chained onto #185 as these two would create a merge-conflict otherwise.
https://github.com/overleaf/issues/issues/3265
Low. Affects debugging of failing joinProject rpcs on already joined connections (not actually supported). 
- run unit/acceptance tests
- editor works
- join not existing doc/project via the browser console -- e.g. `_ide.socket.emit('joinProject', {project_id: '5f0a31aa0e69950001550000'}, console.log)` and see the rpc project_id in the logs.

[misc] fix join project error context

---

app/js/ChannelManager.js
app/js/ConnectedUsersManager.js
app/js/DocumentUpdaterManager.js
app/js/RoomManager.js
app/js/SessionSockets.js
app/js/WebApiManager.js
app/js/WebsocketController.js
test/unit/js/ChannelManagerTests.js
test/unit/js/WebsocketControllerTests.js

Part of https://github.com/overleaf/issues/issues/3265
This PR is split into two parts: the OError.tag migration and then a partial rollback as we noticed that ioredis reused error instances, which lead to attaching tags for unrelated contexts. E.g. `problem marking user as disconnected` and `problem getting clients in project` getting into the same tags array of an `MaxRetriesPerRequestError` instance.
See also this slack thread: https://digital-science.slack.com/archives/C20TZCMMF/p1598000301007200
---
See the docs of OError.tag:
https://github.com/overleaf/o-error#long-stack-traces-with-oerrortag
(currently at 221dd902e7bfa0ee92de1ea5a3cbf3152c3ceeb4)
I am tagging all errors at each async hop. Most of the controller code
will only ever see already tagged errors -- or new errors created …

[misc] migrate to OError tagging/wrapping

---

app/js/WebApiManager.js
app/js/WebsocketController.js
test/unit/js/WebsocketControllerTests.js

For https://github.com/overleaf/issues/issues/3265
The warn entry was missed in the tagging process as it's not directly above a callback.
The errors are logged in `Router._handleError`.
#187 
https://github.com/overleaf/issues/issues/3265
None. Deleted log lines.

[misc] drop duplicate logs

---

app/js/Router.js
app/js/WebApiManager.js
app/js/WebsocketController.js
test/acceptance/js/JoinProjectTests.js
test/acceptance/js/helpers/MockWebServer.js
test/unit/js/WebApiManagerTests.js

For https://github.com/overleaf/issues/issues/3265
One of the last steps for the reworked logging is a re-leveling of error log messages. Specifically those that are _expected_ and hence should not trigger a server-error/sentry issue (level error and above).
Changing the 403 handling is already covered by the frontend.
> Users will get redirected to the login page and will see a 'restricted'
> page after logging in again.
> See frontend: ConnectionManager.reportConnectionError
Changing the 404 handling uses https://github.com/overleaf/web-internal/pull/3143 for a nicer UX (exiting the broken editor).
There is only the [socket.io logging left now](https://console.cloud.google.com/logs/viewer?project=mgcp-1117973-ol-prod&organizationId=753464038511&minLogLevel=0&expandAll=false&timestamp=202 …

[misc] re-level expected error log messages

---

app.js

For https://github.com/overleaf/issues/issues/3373
We are seeing lots of useless log messages from socket.io. Mostly related to bad requests.
This PR is implementing a custom logger for socket.io -- as a replacement for [the built-in logger](https://github.com/overleaf/socket.io/blob/0b7ed64082542638ab1d7d01decb5c3bf46275a0/lib/logger.js) which emits using [console.log](https://github.com/overleaf/socket.io/blob/0b7ed64082542638ab1d7d01decb5c3bf46275a0/lib/logger.js#L78-L84) (which is slow and blocking).
- forward the previously enabled log messages to our logger-module
- stub the previously disabled logger methods
- drop the log-level config for socket.io
All logs are sent to the INFO level and get a context of `{ fromSocketIo: true, originalLevel: level }` in case we want to filter …

[misc] socket.io: use a custom logger

---

app.js

For https://digital-science.slack.com/archives/G6Q45PYQL/p1600778032002300
Previous swallow: #178 
Low. This may turn a previous crash behavior into a memory leak.
Edge case -- it is unknown where and how to trigger it yet.

[app] ignore error from writing to disconnected long-polling client

---

test/acceptance/js/MatrixTests.js
test/acceptance/js/helpers/FixturesManager.js
test/acceptance/js/helpers/MockDocUpdaterServer.js
test/acceptance/js/helpers/MockWebServer.js

Squash of the top commits from https://github.com/overleaf/real-time-internal/pull/9
For https://github.com/overleaf/issues/issues/3295
This PR is implementing a _mini framework_ for testing many kinds of setups in regards to cross client leaks.
The `MatrixTests` test suite is layered with a user stage, session setup stage and finally a stage which performs invalid actions. The _invalid actions_ target a private project (w/o link-sharing).
After these layers I am performing tests similar to the existing test suites: check socket.io room membership, receive updates, receive editor events, send update. 
Sending updates may be extended with different kinds of messages -- e.g. comment ops are treated separately for read-only users and can skip certain auth checks.
Adding items into each stage …

[MatrixTests] add a large testing matrix

---

buildscript.txt
package.json

For https://github.com/overleaf/issues/issues/3529
Reset the custom unit test timeout of 5s back to 2s.
Effectively revert #183 
Low. Affects running unit tests only.

[misc] bump the dev-env to 3.3.5 -- drop custom unit test timeout

---

package.json

We are using `underscore` in `DocumentUpdaterManager` but do not specify an explicit dependency on it. We are implicitly using the `underscore` package of the redis module. Their dependency on `underscore` is removed in v2.
This PR is installing the existing package explicitly. This is separated from the upgrade PR to ease it's review.
https://github.com/overleaf/real-time/blob/b5d5a76555135cc827c2b3092c4cadc8cddad8bd/app/js/DocumentUpdaterManager.js#L5
https://github.com/overleaf/real-time/blob/b5d5a76555135cc827c2b3092c4cadc8cddad8bd/app/js/DocumentUpdaterManager.js#L101
Slightly related to https://github.com/overleaf/issues/issues/3650
Use the same (outdated) version that is already in place.
Low. Only package.json entries.
- test together with the redis upgrade in staging.

[misc] explicitly install underscore

---

app.js
app/js/ChannelManager.js
app/js/DocumentUpdaterController.js
app/js/DocumentUpdaterManager.js
app/js/EventLogger.js
app/js/HealthCheckManager.js
app/js/RoomManager.js
app/js/Router.js
app/js/WebsocketController.js
package-lock.json
package.json
test/unit/js/ChannelManagerTests.js
test/unit/js/DocumentUpdaterControllerTests.js
test/unit/js/DocumentUpdaterManagerTests.js
test/unit/js/EventLoggerTests.js
test/unit/js/RoomManagerTests.js
test/unit/js/WebsocketControllerTests.js

For https://github.com/overleaf/issues/issues/3502
- renamed package from `metrics-sharelatex` to `@overleaf/metrics`
- drop support for statsd backend
- decaffeinate
- compress `/metrics` response using gzip
- bump debugging agents to latest versions
- expose prometheus interfaces for custom metrics (custom tags)
- cleanup of open sockets metrics
- fix deprecation warnings for header access
For https://github.com/overleaf/issues/issues/3502
High. Incomplete metrics collection.
- create a new project
- open a project in the editor
- make changes to a document, reload the editor to check persistence
- compile a project
- open the history tab in the editor
- all services seem to be running fine in the dev-env
- check for compression on the `/metrics` endpoint:
- `$ curl …

[misc] bump metrics module to 3.4.1

---

app/js/DocumentUpdaterManager.js
config/settings.defaults.js
test/unit/js/DocumentUpdaterControllerTests.js
test/unit/js/DocumentUpdaterManagerTests.js

The same as the document update pr, this shards the 'pending-updates-list' key.
I've set the key in settings to 1 for the time being, I can modify this again in a later pr.
https://github.com/overleaf/document-updater/pull/156
https://github.com/overleaf/issues/issues/3955
High - is ops are not processed it will cause the editor to break
I've not worked out a good deployment strategy yet. I am currently thinking about just increasing the document updater count during a quiet time so there are enough processing the 'pending-updates-list' queue, then quickly flip real time to the new sharded key and finally scale down the document updater.

Pending update shard

---

app.js

Added comment about load balancer health checks requiring a 200 response on '/' for real-time.
We already support this with an `app.get('/', (req, res) => res.send('real-time-sharelatex is alive'))` , but I've added a comment so nobody will think this endpoint is redundant and removes it.
NA
https://github.com/overleaf/issues/issues/3402#issuecomment-734865623
https://github.com/overleaf/web-internal/pull/3421
Comment only
None
NA
NA
NA
NA
cc @henryoswald

add comment about health checks on '/'

---

config/settings.test.js

Additional fix to #207 
The mocha run was seemingly not failing even tho some assertions failed. The root cause for the assertions has been addressed in #207 and the PR is addressing the false positive test success.
In production we are attaching an event listener for unhandled exceptions and then shutdown the app. This handler must not run when mocha attaches their own handler.
Note: tests are failing and should fail without the patch in #207. To be rebased onto #207 after it lands.
#207
High. Not attaching the exception handler in production would be fatal. To be tested.
@henryoswald

[misc] let mocha catch errors when running acceptance tests

---

app/js/Router.js

Reduce log noise by lowering log level of `no project_id found on client` messages.
Papercut 32

Lower log level of 'no project_id found on client' messages

---

app.js
app/js/DeploymentManager.js
config/settings.defaults.js

This PR allows real-time to use blue-green deployments behind a load-balancer.
To avoid problems with changes to kubernetes services (which can cause downtime) and changes to pod labels (which can revert if a node or pod is recreated) this uses a configmap to allow the real-time pods to signal to the load balancer whether they are available.
The configmap  specifies the current `deployment_colour`, and the pods monitor it via a file.  The  pod colour is defined via an environment variable at start up.  When the pod colour matches the `deployment_colour` then the pod signals to the load balancer that it is available through the load balancer health checks on `/`, otherwise it removes itself from the load balancer by returning `503 Unavailable` on `/`.
NA …

add blue-green deployment support with load-balancer health-checks

---

app/js/Router.js
app/js/WebsocketController.js

This PR adds the socket.io `transport` type to the main metrics in real-time, so we can see how many clients are connecting via websockets vs xhr-polling.  Currently we don't have this information, so we have been flying blind with the Chrome "websockets over HTTP/2" bug (https://bugs.chromium.org/p/chromium/issues/detail?id=801564).
NA
https://github.com/overleaf/issues/issues/4293
Uses the existing `status` label with `client.transport`.
Metrics only.
NA
cc @gh2k @henryoswald

add transport type to real-time metrics

---

package-lock.json
package.json

fix for exception in client.transport getter, we hit this bug in #217
NA
https://github.com/overleaf/socket.io/pull/6 - fix to socket.io
https://github.com/overleaf/real-time/pull/217 - original PR introducing client.transport
Version upgrade only
Real time metrics, real-time connections
NA
NA
Keep an eye on alerts channel for real-time exceptions
@henryoswald

upgrade to socket.io 0.9.19-overleaf-5

---

package-lock.json
package.json

For https://github.com/overleaf/issues/issues/4544
In Server-CE/Pro we are installing production dependencies only moving forward: https://github.com/overleaf/overleaf/pull/903 .
This in turn requires correct dependency specifications in all the apps. I had hoped that #214 would flag all the missing dependencies, but it did not. See the attached trace-back.
This PR is installing the `bunyan` version of the logger module as production dependency.
```
Error: Cannot find module 'bunyan'
Require stack:
- .../node_modules/@google-cloud/logging-bunyan/build/src/middleware/express.js
- .../node_modules/@google-cloud/logging-bunyan/build/src/index.js
- .../node_modules/logger-sharelatex/logging-manager.js
- .../node_modules/logger-sharelatex/index.js
- .../app.js
```
For …

[misc] install bunyan as production dependency
