overleaf/real-time

app/coffee/Router.coffee
let the client know whether it has successfully authenticated
=> send connectionAccepted/Rejected events on connect

app/coffee/WebsocketController.coffee, test/unit/coffee/WebsocketControllerTests.coffee
avoid sending null project_ids to docupdater
=> handle disconnects of unauthenticated users

app/coffee/DocumentUpdaterManager.coffee, test/unit/coffee/DocumentUpdaterManagerTests.coffee
=> check for null bytes from JSON.stringify

app/coffee/Router.coffee, app/coffee/WebsocketController.coffee
Encodes comments & track changes as ASCII.
=> Encoding changes & comments in ranges

app.coffee, package.json
add support for sentry, this branch was unmerged for a long time
=> add sentry

.gitignore, npm-shrinkwrap.json, package.json
Contributes to: https://github.com/overleaf/sharelatex/issues/1338
=>   Merged Additional issue 1338 for real-time

app/coffee/EventLogger.coffee, test/unit/coffee/DocumentUpdaterControllerTests.coffee, test/unit/coffee/EventLoggerTests.coffee
Fix for https://github.com/sharelatex/real-time-sharelatex/pull/38 to accommodate keys containing `-` (e.g. from hostnames)
https://github.com/sharelatex/real-time-sharelatex/pull/38
=> fix message id parsing

app/coffee/DocumentUpdaterController.coffee
Add a global event rate metric
=> add metric for applied-ops events

npm-shrinkwrap.json, package.json
Update to latest patch level for ioredis.
=> update to redis-sharelatex v1.0.6 for latest ioredis

npm-shrinkwrap.json, package.json
Fixes vulnerability reported by github: `Upgrade request to version 2.68.0 or later.`
> CVE-2017-16026  moderate severity
> Vulnerable versions: >= 2.2.6, < 2.47.0
> Patched version: 2.68.0
> Affected versions of request will disclose local system memory to remote systems in certain circumstances. When a multipart request is made, and the type of body is number, then a buffer of that size will be allocated and sent to the remote server as the body.
NA
https://github.com/sharelatex/real-time-sharelatex/network/alert/package.json/request/open
Updates request module only
High but should be safe.
NA
NA
NA
NA
=> update request module

npm-shrinkwrap.json, package.json, test/acceptance/coffee/ApplyUpdateTests.coffee, test/acceptance/coffee/SessionTests.coffee
bumps redis wrapper and fixes tests which break with the promises returned from ioredis
=> Bump redis with improved logging

app.coffee, app/coffee/DocumentUpdaterController.coffee, app/coffee/WebsocketLoadBalancer.coffee, config/settings.defaults.coffee, package.json
https://github.com/overleaf/google-ops/issues/333
=> Move pubsub to seperate connection

app/coffee/DocumentUpdaterController.coffee, app/coffee/WebsocketLoadBalancer.coffee, config/settings.defaults.coffee
Make event order check a setting and turn it off by default, it is CPU intensive.
NA
https://github.com/overleaf/issues/issues/1801
Small change
Low, disables existing event check.  We can turn it back on if we need to debug this.
NA
NA
NA
NA
@henryoswald
=> make event order check a configuration setting

app.coffee
- removes double `injectMetricsRoute`
- adds http monitor option
=> add health check endpoint and http route logger

app.coffee, app/coffee/DrainManager.coffee, config/settings.defaults.coffee, test/unit/coffee/DrainManagerTests.coffee
Allows us to specify how long a process has to get everyone off the process.
https://github.com/overleaf/google-ops/issues/438
=> add shutdownDrainTimeWindow, drains all connections within time range

config/settings.defaults.coffee
As overleaf/document-updater#96 - add maxRetriesPerRequest setting for ioredis, to config.
Significant, do not deploy
=> Add maxRetriesPerRequest setting for redis

npm-shrinkwrap.json, package.json
Upgrade to the latest version of ioredis
NA
https://github.com/overleaf/web-internal/pull/2233
https://github.com/overleaf/document-updater/pull/95
Version upgrade only
Low
NA
NA
NA
NA
@henryoswald
=> upgrade ioredis to v4.14.1

.github/PULL_REQUEST_TEMPLATE.md, Makefile, buildscript.txt, docker-compose.ci.yml, docker-compose.yml
Clarifies that this is an open source repo and updates the PR template link for contributing.
https://github.com/overleaf/issues/issues/2403
=> Update PR template to reflect current open source docs

npm-shrinkwrap.json, package.json, socket.io.patch.js
Update to the latest patch release of socket.io to see if it helps with the crashes.
See overleaf/issues#1833
=> Update socket.io to latest patch release

Dockerfile, docker-compose.yml
Upgrade to use custom local node image
NA
https://github.com/overleaf/issues/issues/1833
Change to node minor version only. 10.16.3 -> 10.18.1
Realtime, so high, but it's a node minor version bump only.
NA
NA
NA
NA
@mans0954 @das7pad @gh2k
=> upgrade to local node:10.18.1 image

Dockerfile, docker-compose.yml
Upgrade to node:10.19.0, built from source. Will update to public node image when it becomes available
=> update to gcr.io/overleaf-ops/node:10.19.0

app/coffee/DocumentUpdaterController.coffee, app/coffee/DrainManager.coffee, app/coffee/Router.coffee, app/coffee/WebsocketLoadBalancer.coffee
Revert "Merge pull request #91 from overleaf/spd-trycatch-all-the-things"
This reverts commit 2bf7f14f9d050c58f141f465633bb6e274b903dd, reversing
changes made to 989240812532ca43a52513339f4dda8f44a80a64.
https://github.com/overleaf/real-time/pull/91
https://github.com/overleaf/real-time/pull/90
Now we know the problem we can remove these debugging PRs.  Not to merge today, but when things have settled down.
=> Revert debugging PRs for node 10 upgrade

Dockerfile, Jenkinsfile, Makefile, buildscript.txt, docker-compose.ci.yml, docker-compose.yml
Update the build scripts for https://github.com/overleaf/dev-environment/pull/294
This adds a new `base` stage for the docker image.
https://github.com/overleaf/dev-environment/pull/294
- `language=es`
The eslint rules changed in the build-scripts, which required some formatting
changes. These were automatically applied by `prettier-eslint --write`.
- `spelling`
An additional tweak was required to cleanup a pending task for the unit-tests.
- `filestore`,  `spelling` and `third-party-datastore`
See https://github.com/overleaf/dev-environment/pull/294#issuecomment-584777526
for details on the added `data-dir` parameter.
Low.
We will notice any complications in regards to starting the services in staging.
=> [misc] update the build scripts to 1.3.5

buildscript.txt, docker-compose.ci.yml, docker-compose.yml, package-lock.json
Remove dependencies on **mongo** this time.
And rename package lock file.
Low
=> [misc] cleanup dependencies

test/acceptance/coffee/LeaveProjectTests.coffee
This PR adds tests for the redis pub/sub subscribes.
Adding all of them just into the `LeaveProjectTests` was convenient but I can copy the doc related tests into `LeaveDocTests` too.
=> [misc] test/acceptance: LeaveProjectTests: add redis pub/sub tests

app/coffee/WebsocketLoadBalancer.coffee
Followup for #113 
Now that we have synchronous client store access, we can speedup the filtering for restricted clients.
The "distributing event to clients" log message has the actual recipients in the context now.
#113
Low, no changes to test were needed -- which cover the affected lines in depth.
=> [perf] WebsocketLoadBalancer: check is_restricted_message once

app.coffee, config/settings.defaults.coffee
For testing of https://github.com/overleaf/google-ops/pull/859
=> [misc] mount socket.io on a configurable path

app/coffee/WebsocketController.coffee, test/unit/coffee/WebsocketControllerTests.coffee
joinProject should not complete when the redis pub/sub subscribe request
failed.
Low.
=> [WebsocketController] handle redis subscribe error on joinProject

package-lock.json, package.json, test/unit/coffee/AuthorizationManagerTests.coffee, test/unit/coffee/WebApiManagerTests.coffee, test/unit/coffee/WebsocketControllerTests.coffee
sinon v2 has Promise stub support -- backport from #130.
This is in preparation for a follow up PR that backports Promise usage from #133  
#130
#133
Mostly cherry-picking. I added another fix for the unit test of #134 test/unit/coffee/WebsocketControllerTests.coffee line 146.
Low, unit tests only.
=> [misc] backport sinon v2

package-lock.json
For https://github.com/overleaf/issues/issues/3050
https://github.com/overleaf/issues/issues/3050
=> [misc] bump dependencies to latest patch versions

app/coffee/Router.coffee
For https://github.com/overleaf/issues/issues/3067
For https://github.com/overleaf/issues/issues/3067
added `unexpected-arguments`
=> [Router] validate the callback argument

Makefile
⚠️  Highly hacky!
Lint and format are coming very soon thanks to the decaf, but in the
meantime we need steps to pass CI. Updating the build scripts after the
decaf will undo this change.
Needed so it won't block https://github.com/overleaf/issues/issues/3090
=> Add Fake Lint and Format Targets

app/coffee/DocumentUpdaterController.coffee, app/coffee/Router.coffee, app/coffee/WebsocketController.coffee, app/coffee/WebsocketLoadBalancer.coffee, package.json, test/acceptance/coffee/ApplyUpdateTests.coffee, test/acceptance/coffee/ClientTrackingTests.coffee, test/acceptance/coffee/JoinProjectTests.coffee, test/acceptance/coffee/LeaveProjectTests.coffee, test/acceptance/coffee/ReceiveUpdateTests.coffee, test/acceptance/coffee/helpers/RealTimeClient.coffee, test/unit/coffee/DocumentUpdaterControllerTests.coffee, test/unit/coffee/WebsocketControllerTests.coffee, test/unit/coffee/helpers/MockClient.coffee
For https://github.com/overleaf/issues/issues/3115
https://github.com/overleaf/issues/issues/3115
=> [misc] socket.io: use a secondary publicId for public facing usages

app/coffee/DocumentUpdaterController.coffee, app/coffee/Router.coffee, app/coffee/WebsocketController.coffee, app/coffee/WebsocketLoadBalancer.coffee, package.json, test/acceptance/coffee/ApplyUpdateTests.coffee, test/acceptance/coffee/ClientTrackingTests.coffee, test/acceptance/coffee/JoinProjectTests.coffee, test/acceptance/coffee/LeaveProjectTests.coffee, test/acceptance/coffee/ReceiveUpdateTests.coffee, test/acceptance/coffee/helpers/RealTimeClient.coffee, test/unit/coffee/DocumentUpdaterControllerTests.coffee, test/unit/coffee/WebsocketControllerTests.coffee, test/unit/coffee/helpers/MockClient.coffee
For https://github.com/overleaf/issues/issues/3115
https://github.com/overleaf/issues/issues/3115
https://github.com/overleaf/real-time/pull/148
=> [v2] socket.io: use a secondary publicId for public facing usages

app/coffee/Router.coffee
Backport https://github.com/overleaf/real-time/pull/141
https://github.com/overleaf/real-time/pull/141
https://github.com/overleaf/issues/issues/3067
=> [backport] 141: Router: validate the callback argument

socket.io.patch.js
For https://github.com/overleaf/issues/issues/3050
https://github.com/overleaf/issues/issues/3050
=> [perf] add a few short cuts to the packet decoding

app.coffee, app/coffee/SessionSockets.coffee, package-lock.json, package.json, test/acceptance/coffee/SessionSocketsTests.coffee, test/unit/coffee/SessionSocketsTests.coffee
For https://github.com/overleaf/issues/issues/3126
https://github.com/overleaf/issues/issues/3126
=> [misc] vendor a patched session.socket.io middleware

app/coffee/HttpApiController.coffee, app/coffee/Router.coffee, test/acceptance/coffee/DrainManagerTests.coffee, test/acceptance/coffee/helpers/RealTimeClient.coffee
Backport DrainManager acceptance tests from #108 and #112
#108 #112
Low, add new route and adds additional acceptance tests.
=> [backport] 108 and 112: DrainManager acceptance tests

test/acceptance/coffee/ApplyUpdateTests.coffee, test/acceptance/coffee/ReceiveUpdateTests.coffee
Backport #107 and #116 which test cross project leakage and remotely sent ops.
#107 
#116
=> [backport] 107 and 116: Improve ReceiveUpdate acceptance tests

app/js/WebsocketController.js, test/unit/js/RoomManagerTests.js, test/unit/js/WebsocketControllerTests.js
During the decaff cleanup https://github.com/overleaf/real-time/pull/163 I stumbled across a few _broken_ tests and a minor inconsistency in regards to sync/async behavior (calling a callback synchronous in one branch and after a redis call in another branch).
This PR addresses these for separate review of the decaff cleanup changes.
This PR is chained onto the decaff-PR #161 
https://github.com/overleaf/real-time/pull/161
https://github.com/overleaf/real-time/pull/163
Low. The only app change is in the code path of token-access users. The acceptance include cases for these.
=> [misc] fix unit tests

app.js, app/js/AuthorizationManager.js, app/js/ChannelManager.js, app/js/ConnectedUsersManager.js, app/js/DocumentUpdaterController.js, app/js/DocumentUpdaterManager.js, app/js/DrainManager.js, app/js/Errors.js, app/js/EventLogger.js, app/js/HealthCheckManager.js, app/js/HttpApiController.js, app/js/HttpController.js, app/js/RedisClientManager.js, app/js/RoomManager.js, app/js/Router.js, app/js/SafeJsonParse.js, app/js/SessionSockets.js, app/js/WebApiManager.js, app/js/WebsocketController.js, app/js/WebsocketLoadBalancer.js
This PR cleans up the code base after the decaffeinate process #161 . I've left the camelCase rule disabled as it produces a too verbose diff. Instead I will create a follow-up PR which replaces all snake_case usages across all files -- including the `client.ol_context`. 
Chained onto #162 for fixed in the unit tests, which in turn is chained onto the decaff-PR #161.
https://github.com/overleaf/real-time/pull/161
https://github.com/overleaf/real-time/pull/162
I started with a commit per file and moved to a commit per rule/topic for the last 6 file (which was very slow, but here we are).
High, all of real-time. 
- run unit/acceptance tests
- open editor in dev-env
=> [misc] decaff cleanup

app.js, app/js/AuthorizationManager.js, app/js/ChannelManager.js, app/js/ConnectedUsersManager.js, app/js/DocumentUpdaterController.js, app/js/DocumentUpdaterManager.js, app/js/DrainManager.js, app/js/Errors.js, app/js/EventLogger.js, app/js/HealthCheckManager.js, app/js/HttpApiController.js, app/js/HttpController.js, app/js/RedisClientManager.js, app/js/RoomManager.js, app/js/Router.js, app/js/SafeJsonParse.js, app/js/SessionSockets.js, app/js/WebApiManager.js, app/js/WebsocketController.js, app/js/WebsocketLoadBalancer.js
This time I will squash the history.
#163 
This is the same branch as #163 -- see the last commit of this push https://github.com/overleaf/real-time/pull/163#commits-pushed-c0729a3
=> [misc] reland decaff cleanup

app/js/Router.js, config/settings.defaults.js
Reland #165 after decaff cleanup was sqashed #166 .
#165 
Rebased as the git-history of #166 is gone.
=> [misc] reland optionally expose the hostname in the 'debug.getHostname' rpc

package-lock.json, package.json
- Part of https://github.com/overleaf/issues/issues/3095
- High, if something goes wrong
=> Upgrade redis-sharelatex to 1.0.13

app/js/DocumentUpdaterManager.js, app/js/Router.js, app/js/WebsocketController.js, test/unit/js/WebsocketControllerTests.js, test/unit/js/helpers/MockClient.js
For https://github.com/overleaf/issues/issues/3291
https://github.com/overleaf/issues/issues/3291
See https://github.com/overleaf/issues/issues/3291
=> clean up join/leave handling

buildscript.txt
For https://github.com/overleaf/issues/issues/3395
> - dependabot cfg https://github.com/overleaf/dev-environment/pull/371
> - block local npm install https://github.com/overleaf/dev-environment/pull/377 https://github.com/overleaf/dev-environment/pull/380 https://github.com/overleaf/issues/issues/3252
> - drop jenkins cfg https://github.com/overleaf/dev-environment/pull/361 https://github.com/overleaf/dev-environment/pull/370
> - cleanup coffee-script stuff https://github.com/overleaf/dev-environment/pull/361
> - silence npm script invocations https://github.com/overleaf/dev-environment/pull/375
> - bail-out from tests for unhandled promise rejections https://github.com/overleaf/dev-environment/pull/378
> - turn eslint warnings into errors …
=> [misc] bump the dev-env to 3.3.2

LICENSE, package.json
This repo is missing a license file. I copied the license settings from `web`.
Just docs / package changes.
=> Add correct license

test/acceptance/js/ApplyUpdateTests.js
Followup for #205 
The acceptance tests were not aware of the new sharding mechanism. This PR is extending the read and delete process for the keys.
Interestingly this is not a problem when running the tests in Google Cloud Build, but is breaking them locally/in other CI systems.
Local run by @briangough :
<details>
```
applyOtUpdate
when authorized
{"name":"real-time","hostname":"21b6f65829d2","pid":37,"level":50,"err":{"message":"Cannot read property 'should' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'should' of undefined\n    at rclient.lrange.rest (/app/test/acceptance/js/ApplyUpdateTests.js:96:16)\n    at tryCatcher (/app/node_modules/standard-as-callback/built/utils.js:11:23)\n    at promise.then …
```
=> [misc] ApplyUpdateTests: process all the pending-updates-lists
